name: tests and coverage
on: [push, pull_request]
jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - run: pip install hererocks

      - name: check out repository code
        uses: actions/checkout@v2

      - name: run tests and collect code coverage
        run: cd "${{ github.workspace }}" && COVERAGE=1 ./tests/run-for-all-lua-versions.sh

      - name: send code coverage
        run: cd "${{ github.workspace }}" && source "local/hererocks/v-l5.3/bin/activate" && COVERALLS_REPO_TOKEN="${{ secrets.COVERALLS_REPO_TOKEN }}" luacov-coveralls
        env:
          COVERALLS_REPO_TOKEN: ${{ secrets.COVERALLS_REPO_TOKEN }}
