name: tests and coverage
on: [push, pull_request]
jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - run: pip install hererocks

      - name: check out repository code
        uses: actions/checkout@v2

      - name: run tests
        run: cd "${{ github.workspace }}" && COVERAGE=1 ./tests/run-for-all-lua-versions.sh

      - name: Coveralls
        uses: coverallsapp/github-action@master
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          path-to-lcov: ${{ github.workspace }}/luacov.stats.out
